<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>e90ec2e7-fa61-41f9-8ba2-b2825329907a</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation" Version="12.1.1" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.1" />
    <PackageReference Include="MediatR" Version="14.2.0" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.11" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.10" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.10">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.OpenApi" Version="2.11.0" />
    <PackageReference Include="Serilog.AspNetCore" Version="10.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ForumPlatform.Forum.Application\ForumPlatform.Forum.Application.csproj" />
    <ProjectReference Include="..\ForumPlatform.Forum.Infrastructure\ForumPlatform.Forum.Infrastructure.csproj" />
    <ProjectReference Include="..\ForumPlatform.Users.Application\ForumPlatform.Users.Application.csproj" />
    <ProjectReference Include="..\ForumPlatform.Users.Infrastructure\ForumPlatform.Users.Infrastructure.csproj" />
  </ItemGroup>

</Project>
